name: Docs
on:
  push:
    branches:
      - main
      - docs
  pull_request:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Setup Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
      
    - name: Install packages
      run: |
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
        python -m pip install ".[docs]"
      
    - name: Generate Docs
      run: |
        sphinx-apidoc -f -e -o docs/api icecube_data_reader '*test*'
        sphinx-build -M html docs docs/_build

    - name: Setup Pages
      uses: actions/configure-pages@v6

    - name: Upload pages artifacts
      id: deployment
      uses: actions/upload-pages-artifact@v5
      with:
        path: './docs/_build/html'

  deploy:
    name: Deploy docs
    if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
